#include <iostream>
#include <cstdlib>      // for srand() and rand()
#include <ctime>        // for time()

/*
Note that the output generated by the code using rand() is a pseudo-random
number, which means it's not truly random, because it's based on deterministic 
algorithms.
*/

int main() {
    
    std::cout << "********** RANDOM NUMBER GENERATOR **********\n\n";

    // initialize random seed
    std::srand(static_cast<unsigned int>(std::time(0)));

    // define the range for a 5-digit number
    int min = 10000;
    int max = 99999;

    // generate a random number
    int randomNumber = min + std::rand() % (max - min + 1);

    // display the random number
    std::cout << "Random number: " << randomNumber << std::endl;

    std::cout << "\nThank you for using my program.\n";
    std::cout << "**********************************";

    return 0;
}